# Generated by Django 4.2.30 on 2026-07-09 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(blank=True, help_text='Archivo CSV o Excel (.xlsx)', null=True, upload_to='datasources/%Y/%m/')),
                ('target_table', models.SlugField(help_text='Nombre lógico de la tabla destino (identifica los datos importados)', max_length=100)),
                ('environment', models.CharField(choices=[('test', 'Prueba'), ('prod', 'Productivo'), ('demo', 'Demo')], default='test', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='datasources.datasource')),
            ],
            options={
                'ordering': ['data_source', 'row_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('target_table', 'environment'), name='unique_target_table_per_environment'),
        ),
        migrations.AddIndex(
            model_name='importedrow',
            index=models.Index(fields=['data_source', 'row_number'], name='datasources_data_so_80bbac_idx'),
        ),
    ]
