# Generated by Django 4.2.30 on 2026-07-09 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UIString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('es', models.TextField(blank=True)),
                ('it', models.TextField(blank=True)),
                ('en', models.TextField(blank=True)),
                ('notes', models.CharField(blank=True, help_text='Contexto para quien traduzca', max_length=255)),
            ],
            options={
                'verbose_name': 'Texto de interfaz',
                'verbose_name_plural': 'Textos de interfaz (UIStrings)',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.CharField(choices=[('test', 'Prueba'), ('prod', 'Productivo'), ('demo', 'Demo')], default='test', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de entorno',
                'verbose_name_plural': 'Configuración de entorno',
            },
        ),
    ]
