# Generated by Django 4.2.30 on 2026-07-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UIString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('es', models.TextField(blank=True)),
                ('it', models.TextField(blank=True)),
                ('en', models.TextField(blank=True)),
                ('notes', models.CharField(blank=True, help_text='Contexto para quien traduzca', max_length=255)),
            ],
            options={
                'verbose_name': 'Texto de interfaz',
                'verbose_name_plural': 'Textos de interfaz (UIStrings)',
                'ordering': ['key'],
            },
        ),
    ]
