# Generated by Django 4.2.30 on 2026-07-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uistring',
            name='it',
        ),
        migrations.AddField(
            model_name='uistring',
            name='zh',
            field=models.TextField(blank=True),
        ),
    ]
