# Generated by Django 4.2.30 on 2026-07-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_department_exclusionrule_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('url_name', models.CharField(help_text='Nombre de URL Django, ej. gateway:stock', max_length=100)),
                ('group_label', models.CharField(help_text='Título del grupo en el sidebar, ej. Almacén', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['group_label', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='departments', to='gateway.page'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extra_pages',
            field=models.ManyToManyField(blank=True, related_name='granted_profiles', to='gateway.page'),
        ),
    ]
