# Generated by Django 4.2.30 on 2026-07-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_seed_stock_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codpro', models.CharField(max_length=20, unique=True)),
                ('organizacion', models.CharField(blank=True, max_length=150)),
                ('categoria', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Supplier categories',
                'ordering': ['codpro'],
            },
        ),
    ]
