# Generated by Django 4.2.30 on 2026-07-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_seed_stock_tabla_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuecoTipoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('picking', 'Picking'), ('almacenamiento', 'Almacenamiento'), ('ignorar', 'Ignorar (no clasificar)')], default='ignorar', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hueco tipo categorias',
                'ordering': ['descripcion'],
            },
        ),
    ]
