# Generated by Django 4.2.30 on 2026-07-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_ubicacionalmacen_hueco_tipo_por_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huecotipocategoria',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
