# Generated by Django 4.2.30 on 2026-07-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0012_activesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='single_tab_only',
            field=models.BooleanField(default=False, help_text='Bloquea usar la app en más de una pestaña/ventana a la vez con esta cuenta.'),
        ),
    ]
