# Generated by Django 4.2.30 on 2026-07-09 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasources', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Nombre de icono, p.ej. "bar-chart"', max_length=50)),
                ('color', models.CharField(default='#2563eb', help_text='Color hex, p.ej. #2563eb', max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Grupos con acceso a este informe. Vacío = solo staff/superusuarios.', related_name='reports', to='auth.group')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visualization_type', models.CharField(choices=[('table', 'Tabla'), ('bar', 'Gráfico de barras'), ('line', 'Gráfico de líneas'), ('pie', 'Gráfico circular'), ('kpi', 'Indicador (KPI)')], default='table', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuración de la visualización (columnas, ejes, filtros...)')),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_pages', to='datasources.datasource')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='reports.report')),
            ],
            options={
                'ordering': ['report', 'order'],
            },
        ),
    ]
